version: '3.8'

services:

  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
      - "./database/db_data/processed_csvs:/var/lib/setup_data"
      - "./database/db_data/persistent_data:/var/lib/mysql"
    ports:
      - "9906:3306"
    environment:
      # db security is not exactly on lockdown but there's no reason
      # for it to be since it's public data and bound to localhost
      MYSQL_DATABASE: movie_lens
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost

  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - mysql_db
    volumes:
      - ./backend/app:/usr/src/app
    environment:
      MYSQL_DATABASE: movie_lens
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_HOST_IP: mysql_db
    ports:
      - 9000:9000

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
